In [68]:
import pandas as pd
import numpy as np

stroke_data = pd.read_csv('healthcare-dataset-stroke-data.csv')
print(stroke_data.shape)
stroke_data.head()

(5110, 12)


id  gender   age  hypertension  heart_disease ever_married  \
0   9046    Male  67.0             0              1          Yes   
1  51676  Female  61.0             0              0          Yes   
2  31112    Male  80.0             0              1          Yes   
3  60182  Female  49.0             0              0          Yes   
4   1665  Female  79.0             1              0          Yes   

       work_type Residence_type  avg_glucose_level   bmi   smoking_status  \
0        Private          Urban             228.69  36.6  formerly smoked   
1  Self-employed          Rural             202.21   NaN     never smoked   
2        Private          Rural             105.92  32.5     never smoked   
3        Private          Urban             171.23  34.4           smokes   
4  Self-employed          Rural             174.12  24.0     never smoked   

   stroke  
0       1  
1       1  
2       1  
3       1  
4       1

In [69]:
stroke_data.dropna(inplace = True)
print(stroke_data.shape)
stroke_data.head()

(4909, 12)


id  gender   age  hypertension  heart_disease ever_married  \
0   9046    Male  67.0             0              1          Yes   
2  31112    Male  80.0             0              1          Yes   
3  60182  Female  49.0             0              0          Yes   
4   1665  Female  79.0             1              0          Yes   
5  56669    Male  81.0             0              0          Yes   

       work_type Residence_type  avg_glucose_level   bmi   smoking_status  \
0        Private          Urban             228.69  36.6  formerly smoked   
2        Private          Rural             105.92  32.5     never smoked   
3        Private          Urban             171.23  34.4           smokes   
4  Self-employed          Rural             174.12  24.0     never smoked   
5        Private          Urban             186.21  29.0  formerly smoked   

   stroke  
0       1  
2       1  
3       1  
4       1  
5       1

In [70]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
Age = stroke_data['age'].values
Age = Age.reshape(-1, 1)
Age = scaler.fit_transform(Age)

stroke_data['age'] = Age

Avg_Glucose_level = stroke_data['avg_glucose_level'].values
Avg_Glucose_level = Avg_Glucose_level.reshape(-1, 1)
Avg_Glucose_level = scaler.fit_transform(Avg_Glucose_level)

stroke_data['avg_glucose_level'] = Avg_Glucose_level

bmi = stroke_data['bmi'].values
bmi = bmi.reshape(-1, 1)
bmi = scaler.fit_transform(bmi)

stroke_data['bmi'] = bmi

In [72]:
Gender = stroke_data['gender'].values
print(Gender)
for i in range(0, Gender.size):
    if(Gender[i]=='Male'):
        Gender[i] = 1
    elif(Gender[i]=='Female'):
        Gender[i] = 2
    else:
        Gender[i]= 3
print(Gender)

stroke_data['gender'] = Gender

[1 1 2 ... 2 1 2]
[3 3 3 ... 3 3 3]


In [73]:
EM = stroke_data['ever_married'].values

for i in range(0, EM.size):
    if(EM[i]=='Yes'):
        EM[i] = 1
    else:
        EM[i] = 0

print(EM)

stroke_data['ever_married'] = EM

[1 1 1 ... 1 1 1]


In [74]:
WT = stroke_data['work_type'].values
print(WT)

for i in range(0, WT.size):
    if(WT[i]=='Private'):
        WT[i]=1
    elif(WT[i]=='Self-employed'):
        WT[i]=2
    elif(WT[i]=='Never_worked'):
        WT[i]=3
    elif(WT[i]=='Govt_job'):
        WT[i]=4
    else:
        WT[i]=5
        
print(WT)

stroke_data['work_type'] = WT

['Private' 'Private' 'Private' ... 'Self-employed' 'Private' 'Govt_job']
[1 1 1 ... 2 1 4]


In [75]:
RT = stroke_data['Residence_type'].values
print(RT)

for i in range(0, RT.size):
    if(RT[i]=='Urban'):
        RT[i]=1
    else:
        RT[i]=2

print(RT)

stroke_data['Residence_type'] = RT

['Urban' 'Rural' 'Urban' ... 'Rural' 'Rural' 'Urban']
[1 2 1 ... 2 2 1]


In [76]:
SS = stroke_data['smoking_status'].values
print(SS)

for i in range(0, SS.size):
    if(SS[i]=='formerly smoked'):
        SS[i] = 1
    elif(SS[i]=='never smoked'):
        SS[i] = 2
    elif(SS[i]=='smokes'):
        SS[i] = 3
    else:
        SS[i] = 4
        
print(SS)

stroke_data['smoking_status'] = SS

['formerly smoked' 'never smoked' 'smokes' ... 'never smoked'
 'formerly smoked' 'Unknown']
[1 2 3 ... 2 1 4]


In [77]:
stroke_data.head()

id gender       age  hypertension  heart_disease ever_married work_type  \
0   9046      3  1.070138             0              1            1         1   
2  31112      3  1.646563             0              1            1         1   
3  60182      3  0.272012             0              0            1         1   
4   1665      3  1.602222             1              0            1         2   
5  56669      3  1.690903             0              0            1         1   

  Residence_type  avg_glucose_level       bmi smoking_status  stroke  
0              1           2.777698  0.981345              1       1  
2              2           0.013842  0.459269              2       1  
3              1           1.484132  0.701207              3       1  
4              2           1.549193 -0.623083              2       1  
5              1           1.821368  0.013595              1       1

In [78]:
all_features = stroke_data[['gender', 'age', 'hypertension', 'heart_disease', 'ever_married', 'work_type', 'Residence_type', 'avg_glucose_level',
                            'bmi', 'smoking_status']].values
all_classes = stroke_data['stroke'].values

In [79]:
# svm with linear kernel 

from sklearn import svm
from sklearn.model_selection import cross_val_score

model = svm.SVC(kernel = 'linear', C = 1.0)
scores = cross_val_score(model, all_features, all_classes, cv = 10)
scores.mean()

0.9574254956565111

In [80]:
# Naive Bayes

from sklearn.naive_bayes import MultinomialNB
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
all_features_MinMax = scaler.fit_transform(all_features)

nb = MultinomialNB()
scores = cross_val_score(nb, all_features_MinMax, all_classes, cv = 10)
scores.mean()

0.9574254956565111

In [81]:
# DecisionTree

from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier()
scores = cross_val_score(model, all_features, all_classes, cv = 10)
scores.mean()

0.9183116505257909

In [88]:
# Neural Network

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout

def model_NN():
    model = Sequential()
    model.add(Dense(15, input_dim = 10, kernel_initializer = 'normal', activation = 'relu'))
    model.add(Dense(5, kernel_initializer = 'normal', activation = 'relu'))
    model.add(Dense(1, kernel_initializer = 'normal', activation = 'sigmoid'))
    model.compile(loss = 'binary_crossentropy', optimizer = 'adam', metrics = ['accuracy'])
    return model

In [89]:
from tensorflow.keras.wrappers.scikit_learn import KerasClassifier

estimator = KerasClassifier(build_fn = model_NN, epochs = 75, verbose = 0)
scores = cross_val_score(estimator, all_features_MinMax, all_classes, cv = 10)
scores.mean()

0.9574338078498841